### ISSUE TITLE
Link failed.

### ISSUE THREAD

**Issue by luciddream-tsin** [tippesi/Atlas-Engine#54]
```

Jolt.lib(JobSystemThreadPool.cpp.obj) : error LNK2019: unresolved external symbol _Thrd_sleep_for referenced in function 
"void __cdecl std::this_thread::sleep_until<struct std::chrono::steady_clock,class std::chrono::duration<__int64,struct std::ratio<1,1000000000>>>(class std::chrono::time_point<struct std::chrono::steady_clock,class std::chrono::duration<__int64,struct std::ratio<1,1000000000>>> const & ...

```

IDE :CLion, Compiler: MSVC, OS:Windows11,

**Comment by YanbingXu** [comment]
您好，我已收到邮件，谢谢！

**Comment by tippesi** [comment]
Thank you for opening this issue and sorry for the late reply. I encountered this issue before in the build pipeline and from what I remember it was an issue with that specific MSVC version. Could you try to upgrade to a newer version? Hope that helps

**Comment by tippesi** [comment]
Great, good to hear. I’m closing this issue
